# _config.yml
title: "Modelica Lab"
description: "A comprehensive curriculum on Modelica and OpenModelica."
baseurl: "/modelica-lab"  # Replace with your repository name
url: "https://hirca.github.io"
theme: minima
plugins:
  - jekyll-toc
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter_opts:
    block:
      line_numbers: true

