# Site settings
title: Modelica Lab
description: A learning resource for Modelica
theme: jekyll-theme-minimal

# Navigation
nav:
  - title: Home
    url: /
  - title: Learning Modules
    url: /learning-modules/
  - title: Library
    url: /library/
  - title: Exercises
    url: /exercises/
  - title: Projects
    url: /projects/

# Collections
collections:
  modules:
    output: true
    permalink: /learning-modules/:path/

# Defaults
defaults:
  - scope:
      path: "docs/learning-modules"
      type: "pages"
    values:
      layout: "module"
